import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useRef, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLab } from "@/lib/store";
import type { Analyte } from "@/lib/lab-types";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { ChromatogramPlot } from "@/components/chromatogram-plot";
import { PeakTable } from "@/components/peak-table";
import { FileText, Download, Loader2, Share2, Trash2, ChevronUp, ChevronDown } from "lucide-react";
import { toast } from "sonner";
import {
  createReport,
  createUploadUrl,
  deleteReport,
  getReportSignedUrl,
  getRunEICBatch,
  listReports,
} from "@/lib/lab.functions";
import { renderReportPdf } from "@/lib/pdf-report";
import { ShareDialog } from "@/components/share-dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export const Route = createFileRoute("/_shell/reports")({
  component: Reports,
});

function Reports() {
  const { runs, methods, analytes, columns } = useLab();
  const [methodId, setMethodId] = useState(methods[0]?.id ?? "");
  const [sections, setSections] = useState({
    method: true,
    column: true,
    gradientTable: true,
    gradientPlot: true,
    chromatogram: true,
    peaks: true,
    eics: true,
    notes: true,
  });
  type SectionKey = keyof typeof sections;
  const SECTION_LABELS: Record<SectionKey, string> = {
    method: "Method parameters",
    column: "Column (type & dimensions)",
    gradientTable: "Gradient timetable",
    gradientPlot: "Gradient plot",
    chromatogram: "Chromatogram (TIC)",
    peaks: "Peak table",
    eics: "Extracted ion chromatograms",
    notes: "Notes",
  };
  const [sectionOrder, setSectionOrder] = useState<SectionKey[]>([
    "method",
    "column",
    "gradientTable",
    "gradientPlot",
    "chromatogram",
    "peaks",
    "eics",
    "notes",
  ]);
  const moveSection = (idx: number, dir: -1 | 1) => {
    setSectionOrder((prev) => {
      const j = idx + dir;
      if (j < 0 || j >= prev.length) return prev;
      const next = prev.slice();
      [next[idx], next[j]] = [next[j], next[idx]];
      return next;
    });
  };
  const [selectedEicIds, setSelectedEicIds] = useState<Set<string>>(new Set());
  const [customNotes, setCustomNotes] = useState("");
  const [reportTitle, setReportTitle] = useState("");
  const [reportFooter, setReportFooter] = useState("Generated By ChromaFlow");
  const [busy, setBusy] = useState(false);
  const printRef = useRef<HTMLDivElement | null>(null);

  const method = methods.find((m) => m.id === methodId);
  const methodRun = runs.find((r) => r.methodId === methodId);
  const column = columns.find((c) => c.id === method?.columnId);
  const effectiveTitle = reportTitle.trim() || method?.name || "Method Report";

  const uploadFn = useServerFn(createUploadUrl);
  const createReportFn = useServerFn(createReport);
  const listReportsFn = useServerFn(listReports);
  const getReportUrlFn = useServerFn(getReportSignedUrl);
  const deleteReportFn = useServerFn(deleteReport);
  const getEicBatchFn = useServerFn(getRunEICBatch);
  const qc = useQueryClient();

  const reportsQuery = useQuery({
    queryKey: ["reports"],
    queryFn: () => listReportsFn(),
  });

  const eicCandidates = useMemo(
    () => analytes.filter((a: Analyte) => Number.isFinite(a.mz) && a.mz > 0),
    [analytes],
  );
  const selectedEicAnalytes = useMemo(
    () => eicCandidates.filter((a: Analyte) => selectedEicIds.has(a.id)),
    [eicCandidates, selectedEicIds],
  );

  const hasScans = !!methodRun?.scansBlobPath;
  const eicQuery = useQuery({
    queryKey: [
      "report-eics",
      methodRun?.id,
      selectedEicAnalytes.map((a) => a.id).join(","),
    ],
    enabled: hasScans && sections.eics && selectedEicAnalytes.length > 0,
    queryFn: () =>
      getEicBatchFn({
        data: {
          runId: methodRun!.id,
          ppm: 10,
          targets: selectedEicAnalytes.map((a) => ({ id: a.id, mz: a.mz })),
        },
      }),
  });


  const generate = async () => {
    if (!printRef.current || !method) return;
    setBusy(true);
    try {
      const blob = await renderReportPdf(printRef.current);
      const filename = `${effectiveTitle.replace(/\s+/g, "_")}.pdf`;
      let up;
      try {
        up = await uploadFn({ data: { filename, bucket: "reports" } });
      } catch (e: any) {
        const msg = e?.message ?? "";
        if (/bucket.*not.*found|not_found/i.test(msg)) {
          throw new Error(
            "Reports storage bucket missing. Re-run the Phase 3 SQL migration to create it.",
          );
        }
        throw e;
      }
      const putRes = await fetch(up.signedUrl, {
        method: "PUT",
        headers: { "Content-Type": "application/pdf" },
        body: blob,
      });
      if (!putRes.ok) {
        const detail = await putRes.text().catch(() => "");
        throw new Error(
          `Upload failed (${putRes.status})${detail ? `: ${detail.slice(0, 160)}` : ""}`,
        );
      }
      const report = await createReportFn({
        data: {
          title: effectiveTitle,
          template: "method",
          runIds: methodRun ? [methodRun.id] : [],
          storagePath: up.path,
        },
      });
      if ((report as any)?.metadataComplete === false) {
        toast.warning("PDF generated, but report history was not saved because the reports table migration is incomplete.");
      } else {
        toast.success("Report saved");
      }
      qc.invalidateQueries({ queryKey: ["reports"] });
    } catch (e: any) {
      toast.error(e?.message ?? "Failed to generate PDF");
    } finally {
      setBusy(false);
    }
  };

  const downloadReport = async (id: string, title: string) => {
    try {
      const { url } = await getReportUrlFn({ data: { id } });
      const a = document.createElement("a");
      a.href = url;
      a.target = "_blank";
      a.rel = "noopener";
      a.download = `${title}.pdf`;
      a.click();
    } catch (e: any) {
      toast.error(e?.message ?? "Failed to fetch download URL");
    }
  };

  const removeReport = async (id: string, title: string) => {
    if (!confirm(`Delete report "${title}"? This cannot be undone.`)) return;
    try {
      await deleteReportFn({ data: { id } });
      toast.success("Report deleted");
      qc.invalidateQueries({ queryKey: ["reports"] });
    } catch (e: any) {
      toast.error(e?.message ?? "Failed to delete report");
    }
  };


  return (
    <div className="flex flex-col gap-4 p-6">
      <div className="flex items-end justify-between">
        <div>
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
            Reporting
          </div>
          <h1 className="mt-1 text-2xl font-semibold tracking-tight">Report builder</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Compose PDF reports from method parameters, chromatograms and peak tables.
          </p>
        </div>
        <div className="flex flex-col items-end gap-1">
          <Button onClick={generate} disabled={busy || !method}>
            {busy ? (
              <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" />
            ) : (
              <Download className="mr-1 h-3.5 w-3.5" />
            )}
            {busy ? "Generating…" : "Generate PDF"}
          </Button>
          {!method && (
            <div className="text-[10px] text-muted-foreground">Select a method first.</div>
          )}
          {method && !methodRun && (
            <div className="text-[10px] text-[color:var(--status-warn)]">
              No run is linked to this method — chromatogram & peaks will be omitted.
            </div>
          )}
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
        <Card className="h-fit border-border bg-card p-4">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
            Subject
          </div>
          <div className="mt-2 space-y-1">
            {methods.map((m) => (
              <button
                key={m.id}
                onClick={() => setMethodId(m.id)}
                className={`w-full rounded-md px-2 py-1.5 text-left text-xs ${
                  methodId === m.id ? "bg-primary/15 text-primary" : "hover:bg-accent/30"
                }`}
              >
                {m.name}
              </button>
            ))}
          </div>
          <div className="mt-5 text-[10px] uppercase tracking-widest text-muted-foreground">
            Header & footer
          </div>
          <div className="mt-2 space-y-2">
            <div>
              <label className="text-[10px] text-muted-foreground">Title</label>
              <Input
                value={reportTitle}
                onChange={(e) => setReportTitle(e.target.value)}
                placeholder={method?.name ?? "Report title"}
                className="mt-1 h-8 text-xs"
              />
            </div>
            <div>
              <label className="text-[10px] text-muted-foreground">Footer</label>
              <Input
                value={reportFooter}
                onChange={(e) => setReportFooter(e.target.value)}
                placeholder="Generated By ChromaFlow"
                className="mt-1 h-8 text-xs"
              />
            </div>
          </div>

          <div className="mt-5 flex items-center justify-between text-[10px] uppercase tracking-widest text-muted-foreground">
            <span>Sections</span>
            <span className="normal-case tracking-normal">Drag order via ↑ ↓</span>
          </div>
          <div className="mt-2 space-y-1">
            {sectionOrder.map((key, idx) => (
              <div
                key={key}
                className="flex items-center gap-1 rounded-md px-1 py-0.5 hover:bg-accent/20"
              >
                <Checkbox
                  checked={sections[key]}
                  onCheckedChange={(v) => setSections({ ...sections, [key]: !!v })}
                />
                <span className="flex-1 text-xs">{SECTION_LABELS[key]}</span>
                <button
                  type="button"
                  onClick={() => moveSection(idx, -1)}
                  disabled={idx === 0}
                  className="rounded p-0.5 text-muted-foreground hover:bg-accent/40 hover:text-foreground disabled:opacity-30"
                  aria-label={`Move ${SECTION_LABELS[key]} up`}
                >
                  <ChevronUp className="h-3 w-3" />
                </button>
                <button
                  type="button"
                  onClick={() => moveSection(idx, 1)}
                  disabled={idx === sectionOrder.length - 1}
                  className="rounded p-0.5 text-muted-foreground hover:bg-accent/40 hover:text-foreground disabled:opacity-30"
                  aria-label={`Move ${SECTION_LABELS[key]} down`}
                >
                  <ChevronDown className="h-3 w-3" />
                </button>
              </div>
            ))}
          </div>

          {sections.notes && (
            <div className="mt-4">
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Custom notes
              </div>
              <Textarea
                value={customNotes}
                onChange={(e) => setCustomNotes(e.target.value)}
                placeholder="Add your own notes to include in the report…"
                className="mt-2 h-28 text-xs"
              />
            </div>
          )}

          {sections.eics && (
            <>
              <div className="mt-5 flex items-center justify-between text-[10px] uppercase tracking-widest text-muted-foreground">
                <span>EIC analytes</span>
                <span className="font-mono normal-case tracking-normal text-muted-foreground">
                  {selectedEicIds.size}/{eicCandidates.length}
                </span>
              </div>
              {!hasScans && (
                <div className="mt-2 rounded-md border border-border bg-muted/30 p-2 text-[10px] text-muted-foreground">
                  Selected run has no raw scans blob — EICs can't be extracted.
                </div>
              )}
              {hasScans && eicCandidates.length === 0 && (
                <div className="mt-2 rounded-md border border-border bg-muted/30 p-2 text-[10px] text-muted-foreground">
                  No analytes with an m/z in the library yet.
                </div>
              )}
              {hasScans && eicCandidates.length > 0 && (
                <>
                  <div className="mt-1 flex gap-2 text-[10px]">
                    <button
                      type="button"
                      className="text-primary hover:underline"
                      onClick={() =>
                        setSelectedEicIds(new Set(eicCandidates.map((a) => a.id)))
                      }
                    >
                      Select all
                    </button>
                    <span className="text-muted-foreground">·</span>
                    <button
                      type="button"
                      className="text-primary hover:underline"
                      onClick={() => setSelectedEicIds(new Set())}
                    >
                      Clear
                    </button>
                  </div>
                  <ScrollArea className="mt-2 h-56 rounded-md border border-border">
                    <div className="space-y-1 p-2 pr-3">
                      {eicCandidates.map((a) => (
                        <label
                          key={a.id}
                          className="flex cursor-pointer items-center gap-2 text-xs"
                        >
                          <Checkbox
                            checked={selectedEicIds.has(a.id)}
                            onCheckedChange={(v) =>
                              setSelectedEicIds((prev) => {
                                const next = new Set(prev);
                                if (v) next.add(a.id);
                                else next.delete(a.id);
                                return next;
                              })
                            }
                          />
                          <span className="min-w-0 flex-1 truncate">{a.name}</span>
                          <span className="shrink-0 font-mono text-[10px] text-muted-foreground">
                            {a.mz.toFixed(3)}
                          </span>
                        </label>
                      ))}
                    </div>
                  </ScrollArea>
                </>
              )}
            </>
          )}
        </Card>

        <Card className="border-border bg-surface-elevated p-6">
          <div
            ref={printRef}
            className="mx-auto max-w-3xl space-y-6 rounded-md bg-card p-8 shadow-lg"
          >
            <div className="flex items-center justify-between border-b border-border pb-3">
              <div>
                <div className="text-[10px] uppercase tracking-[0.2em] text-primary">
                  CHROMA.LAB · Method Report
                </div>
                <h2 className="mt-1 text-lg font-semibold">{effectiveTitle}</h2>
              </div>
              <FileText className="h-5 w-5 text-muted-foreground" />
            </div>

            {sectionOrder.map((key) => {
              if (!sections[key]) return null;
              switch (key) {
                case "method":
                  return method ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Method parameters
                      </h3>
                      <dl className="mt-2 grid grid-cols-2 gap-x-6 gap-y-2 font-mono text-xs">
                        <RField label="Modality" value={method.modality} />
                        <RField label="Ionization" value={method.msIonization} />
                        <RField label="Mobile phase A" value={method.mobilePhaseA} />
                        <RField label="Mobile phase B" value={method.mobilePhaseB} />
                        <RField label="Flow" value={`${method.flowRate} mL/min`} />
                        <RField label="Column temp" value={`${method.columnTemp} °C`} />
                      </dl>
                    </section>
                  ) : null;
                case "column":
                  return column ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Column
                      </h3>
                      <dl className="mt-2 grid grid-cols-2 gap-x-6 gap-y-2 font-mono text-xs">
                        <RField label="Name" value={column.name} />
                        <RField label="Chemistry / type" value={column.chemistry} />
                        <RField label="Dimensions" value={column.dimensions} />
                        <RField label="Particle size" value={column.particleSize} />
                        <RField label="Manufacturer" value={column.manufacturer} />
                        <RField label="Serial" value={column.serial} />
                      </dl>
                    </section>
                  ) : null;
                case "gradientTable":
                  return method && method.gradient.length > 0 ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Gradient timetable
                      </h3>
                      <Table className="mt-2">
                        <TableHeader>
                          <TableRow className="bg-muted/30 hover:bg-muted/30">
                            <TableHead className="text-[10px] uppercase tracking-wider">Time (min)</TableHead>
                            <TableHead className="text-[10px] uppercase tracking-wider">% B</TableHead>
                            <TableHead className="text-[10px] uppercase tracking-wider">Flow (mL/min)</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {method.gradient.map((g, i) => (
                            <TableRow key={i} className="font-mono text-xs">
                              <TableCell className="py-1.5">{g.time.toFixed(1)}</TableCell>
                              <TableCell className="py-1.5">{g.pctB}</TableCell>
                              <TableCell className="py-1.5">{g.flow.toFixed(2)}</TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </section>
                  ) : null;
                case "gradientPlot":
                  return method && method.gradient.length > 1 ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Gradient plot
                      </h3>
                      <div className="mt-2 rounded-md border border-border p-2">
                        <GradientPlot gradient={method.gradient} />
                      </div>
                    </section>
                  ) : null;
                case "chromatogram":
                  return methodRun ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Representative chromatogram
                      </h3>
                      <div className="mt-2 rounded-md border border-border p-2">
                        <ChromatogramPlot runs={[methodRun]} height={200} showPeaks />
                      </div>
                      <div className="mt-1 font-mono text-[10px] text-muted-foreground">
                        {methodRun.name}
                      </div>
                    </section>
                  ) : null;
                case "peaks":
                  return methodRun ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Peak table
                      </h3>
                      <div className="mt-2">
                        <PeakTable peaks={methodRun.peaks.slice(0, 8)} />
                      </div>
                    </section>
                  ) : null;
                case "eics":
                  return methodRun && selectedEicAnalytes.length > 0 ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Extracted ion chromatograms
                      </h3>
                      {!hasScans ? (
                        <div className="mt-2 text-[11px] text-muted-foreground">
                          Run has no raw scans blob — EICs unavailable.
                        </div>
                      ) : eicQuery.isLoading ? (
                        <div className="mt-2 text-[11px] text-muted-foreground">
                          Extracting {selectedEicAnalytes.length} EIC trace(s)…
                        </div>
                      ) : eicQuery.isError ? (
                        <div className="mt-2 text-[11px] text-destructive">
                          Failed to load EICs.
                        </div>
                      ) : (
                        <EicReportBlock
                          analytes={selectedEicAnalytes}
                          data={eicQuery.data}
                        />
                      )}
                    </section>
                  ) : null;
                case "notes":
                  return method ? (
                    <section key={key}>
                      <h3 className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
                        Notes
                      </h3>
                      <p className="mt-2 text-xs text-muted-foreground">{method.notes}</p>
                      {customNotes.trim() && (
                        <div className="mt-3 rounded-md border border-border bg-muted/20 p-2">
                          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                            Analyst notes
                          </div>
                          <p className="mt-1 whitespace-pre-wrap text-xs">{customNotes}</p>
                        </div>
                      )}
                      <div className="mt-2 flex flex-wrap gap-1">
                        {method.tags.map((t) => (
                          <Badge key={t} variant="outline" className="text-[10px]">
                            {t}
                          </Badge>
                        ))}
                      </div>
                    </section>
                  ) : null;
                default:
                  return null;
              }
            })}

            <div className="border-t border-border pt-2 text-[9px] text-muted-foreground">
              {(reportFooter.trim() || "Generated By ChromaFlow")} · {new Date().toLocaleDateString()}
            </div>
          </div>
        </Card>
      </div>

      <Card className="border-border bg-card p-0">
        <div className="border-b border-border px-4 py-3">
          <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
            Past reports
          </div>
          <h2 className="text-sm font-semibold">All generated PDFs</h2>
        </div>
        <div className="divide-y divide-border">
          {reportsQuery.isLoading && (
            <div className="px-4 py-3 text-xs text-muted-foreground">Loading…</div>
          )}
          {!reportsQuery.isLoading && (reportsQuery.data ?? []).length === 0 && (
            <div className="px-4 py-6 text-center text-xs text-muted-foreground">
              No reports yet. Generate one above.
            </div>
          )}
          {(reportsQuery.data ?? []).filter((r: any) => r.storage_path).map((r: any) => (
            <div
              key={r.id}
              className="flex items-center justify-between px-4 py-2 text-xs"
            >
              <div className="flex items-center gap-2">
                <FileText className="h-3.5 w-3.5 text-muted-foreground" />
                <span className="font-medium">{r.title}</span>
                <Badge variant="outline" className="text-[10px] capitalize">
                  {r.template}
                </Badge>
                <span className="font-mono text-[10px] text-muted-foreground">
                  {new Date(r.created_at).toLocaleString()}
                </span>
              </div>
              <div className="flex items-center gap-1">
                <ShareDialog
                  resourceKind="report"
                  resourceId={r.id}
                  trigger={
                    <Button size="sm" variant="outline">
                      <Share2 className="mr-1 h-3.5 w-3.5" /> Share
                    </Button>
                  }
                />
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => downloadReport(r.id, r.title)}
                >
                  <Download className="mr-1 h-3.5 w-3.5" /> Download
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => removeReport(r.id, r.title)}
                  className="text-destructive hover:text-destructive"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </Button>

              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

function RField({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-[9px] uppercase tracking-widest text-muted-foreground">{label}</dt>
      <dd className="mt-0.5">{value}</dd>
    </div>
  );
}

type EicBatch = {
  x: number[];
  traces: Array<{
    id: string;
    mz: number;
    y: number[];
    peakRt: number | null;
    peakIntensity: number;
    area: number;
    fwhm: number;
    sn: number;
  }>;
};

function EicReportBlock({
  analytes,
  data,
}: {
  analytes: Analyte[];
  data: EicBatch | undefined;
}) {
  if (!data || data.traces.length === 0) {
    return <div className="mt-2 text-[11px] text-muted-foreground">No EIC data.</div>;
  }
  const nameById = new Map(analytes.map((a) => [a.id, a.name]));
  const overlayRuns = data.traces.map((t) => ({
    id: t.id,
    name: nameById.get(t.id) ?? "?",
    trace: { x: data.x, tic: t.y, bpc: t.y },
  }));
  return (
    <>
      <div className="mt-2 rounded-md border border-border p-2">
        <ChromatogramPlot runs={overlayRuns} height={220} />
      </div>
      <table className="mt-3 w-full text-[10px]">
        <thead>
          <tr className="border-b border-border text-left text-muted-foreground">
            <th className="py-1 font-medium uppercase tracking-widest">Analyte</th>
            <th className="py-1 font-mono font-medium uppercase tracking-widest">m/z</th>
            <th className="py-1 text-right font-mono font-medium uppercase tracking-widest">
              RT
            </th>
            <th className="py-1 text-right font-mono font-medium uppercase tracking-widest">
              Height
            </th>
            <th className="py-1 text-right font-mono font-medium uppercase tracking-widest">
              Area
            </th>
            <th className="py-1 text-right font-mono font-medium uppercase tracking-widest">
              FWHM
            </th>
            <th className="py-1 text-right font-mono font-medium uppercase tracking-widest">
              S/N
            </th>
          </tr>
        </thead>
        <tbody>
          {data.traces.map((t) => (
            <tr key={t.id} className="border-b border-border/60">
              <td className="py-1">{nameById.get(t.id) ?? "?"}</td>
              <td className="py-1 font-mono">{t.mz.toFixed(4)}</td>
              <td className="py-1 text-right font-mono">
                {t.peakRt != null ? t.peakRt.toFixed(2) : "—"}
              </td>
              <td className="py-1 text-right font-mono">
                {t.peakIntensity ? t.peakIntensity.toExponential(2) : "—"}
              </td>
              <td className="py-1 text-right font-mono">
                {t.area ? t.area.toExponential(2) : "—"}
              </td>
              <td className="py-1 text-right font-mono">
                {t.fwhm ? t.fwhm.toFixed(3) : "—"}
              </td>
              <td className="py-1 text-right font-mono">
                {t.sn ? t.sn.toFixed(1) : "—"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
}

function GradientPlot({
  gradient,
}: {
  gradient: { time: number; pctB: number; flow: number }[];
}) {
  const w = 560;
  const h = 180;
  const padL = 36;
  const padR = 36;
  const padT = 10;
  const padB = 26;
  const pts = [...gradient].sort((a, b) => a.time - b.time);
  const tMin = pts[0].time;
  const tMax = pts[pts.length - 1].time;
  const tSpan = Math.max(0.001, tMax - tMin);
  const flowMax = Math.max(...pts.map((p) => p.flow));
  const flowMin = Math.min(...pts.map((p) => p.flow));
  const flowSpan = Math.max(0.001, flowMax - flowMin);
  const xOf = (t: number) => padL + ((t - tMin) / tSpan) * (w - padL - padR);
  const yB = (b: number) => padT + (1 - b / 100) * (h - padT - padB);
  const yF = (f: number) =>
    padT + (1 - (f - flowMin) / flowSpan) * (h - padT - padB);
  const bPath = pts.map((p, i) => `${i ? "L" : "M"}${xOf(p.time)},${yB(p.pctB)}`).join(" ");
  const fPath = pts.map((p, i) => `${i ? "L" : "M"}${xOf(p.time)},${yF(p.flow)}`).join(" ");
  const yTicks = [0, 25, 50, 75, 100];
  const tTicks = 5;
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full" role="img" aria-label="Gradient plot">
      {yTicks.map((b) => (
        <g key={b}>
          <line
            x1={padL}
            x2={w - padR}
            y1={yB(b)}
            y2={yB(b)}
            stroke="currentColor"
            strokeOpacity={0.08}
          />
          <text
            x={padL - 4}
            y={yB(b) + 3}
            textAnchor="end"
            fontSize="9"
            fill="currentColor"
            opacity={0.55}
          >
            {b}
          </text>
        </g>
      ))}
      {Array.from({ length: tTicks + 1 }).map((_, i) => {
        const t = tMin + (i / tTicks) * tSpan;
        return (
          <text
            key={i}
            x={xOf(t)}
            y={h - padB + 14}
            textAnchor="middle"
            fontSize="9"
            fill="currentColor"
            opacity={0.55}
          >
            {t.toFixed(1)}
          </text>
        );
      })}
      <text
        x={padL - 28}
        y={padT + 8}
        fontSize="9"
        fill="currentColor"
        opacity={0.7}
      >
        % B
      </text>
      <text
        x={w - padR + 4}
        y={padT + 8}
        fontSize="9"
        fill="currentColor"
        opacity={0.7}
      >
        Flow
      </text>
      <text
        x={(w - padL - padR) / 2 + padL}
        y={h - 4}
        textAnchor="middle"
        fontSize="9"
        fill="currentColor"
        opacity={0.7}
      >
        Time (min)
      </text>
      <path d={bPath} fill="none" stroke="hsl(var(--primary))" strokeWidth={1.75} />
      <path
        d={fPath}
        fill="none"
        stroke="currentColor"
        strokeOpacity={0.55}
        strokeWidth={1.25}
        strokeDasharray="3 3"
      />
      {pts.map((p, i) => (
        <circle key={i} cx={xOf(p.time)} cy={yB(p.pctB)} r={2} fill="hsl(var(--primary))" />
      ))}
      <g transform={`translate(${w - padR - 110}, ${padT + 4})`}>
        <rect width={110} height={28} fill="white" fillOpacity={0.6} rx={3} />
        <line x1={6} x2={20} y1={10} y2={10} stroke="hsl(var(--primary))" strokeWidth={1.75} />
        <text x={24} y={13} fontSize="9" fill="currentColor">% B</text>
        <line
          x1={56}
          x2={70}
          y1={10}
          y2={10}
          stroke="currentColor"
          strokeOpacity={0.55}
          strokeWidth={1.25}
          strokeDasharray="3 3"
        />
        <text x={74} y={13} fontSize="9" fill="currentColor">Flow</text>
      </g>
    </svg>
  );
}
