/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellOverlayRouteImport } from './routes/_shell.overlay'
import { Route as ShellBatchesRouteImport } from './routes/_shell.batches'
import { Route as ShellAnalytesRouteImport } from './routes/_shell.analytes'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'
import { Route as ShellAccountRouteImport } from './routes/_shell.account'
import { Route as ShellRunsIndexRouteImport } from './routes/_shell.runs.index'
import { Route as ShellMethodsIndexRouteImport } from './routes/_shell.methods.index'
import { Route as ShellColumnsIndexRouteImport } from './routes/_shell.columns.index'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public/config'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthResetRequestRouteImport } from './routes/api/auth/reset-request'
import { Route as ApiAuthResetRouteImport } from './routes/api/auth/reset'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ShellRunsRunIdRouteImport } from './routes/_shell.runs.$runId'
import { Route as ShellMethodsNewRouteImport } from './routes/_shell.methods.new'
import { Route as ShellMethodsCompareRouteImport } from './routes/_shell.methods.compare'
import { Route as ShellMethodsMethodIdRouteImport } from './routes/_shell.methods.$methodId'
import { Route as ShellColumnsColumnIdRouteImport } from './routes/_shell.columns.$columnId'
import { Route as ShellAnalytesAnalyteIdRouteImport } from './routes/_shell.analytes.$analyteId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOverlayRoute = ShellOverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBatchesRoute = ShellBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalytesRoute = ShellAnalytesRouteImport.update({
  id: '/analytes',
  path: '/analytes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountRoute = ShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRunsIndexRoute = ShellRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMethodsIndexRoute = ShellMethodsIndexRouteImport.update({
  id: '/methods/',
  path: '/methods/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellColumnsIndexRoute = ShellColumnsIndexRouteImport.update({
  id: '/columns/',
  path: '/columns/',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public/config',
  path: '/api/public/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetRequestRoute = ApiAuthResetRequestRouteImport.update({
  id: '/api/auth/reset-request',
  path: '/api/auth/reset-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetRoute = ApiAuthResetRouteImport.update({
  id: '/api/auth/reset',
  path: '/api/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRunsRunIdRoute = ShellRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMethodsNewRoute = ShellMethodsNewRouteImport.update({
  id: '/methods/new',
  path: '/methods/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMethodsCompareRoute = ShellMethodsCompareRouteImport.update({
  id: '/methods/compare',
  path: '/methods/compare',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMethodsMethodIdRoute = ShellMethodsMethodIdRouteImport.update({
  id: '/methods/$methodId',
  path: '/methods/$methodId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellColumnsColumnIdRoute = ShellColumnsColumnIdRouteImport.update({
  id: '/columns/$columnId',
  path: '/columns/$columnId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalytesAnalyteIdRoute = ShellAnalytesAnalyteIdRouteImport.update({
  id: '/$analyteId',
  path: '/$analyteId',
  getParentRoute: () => ShellAnalytesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof ShellAccountRoute
  '/admin': typeof ShellAdminRoute
  '/analytes': typeof ShellAnalytesRouteWithChildren
  '/batches': typeof ShellBatchesRoute
  '/overlay': typeof ShellOverlayRoute
  '/reports': typeof ShellReportsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/analytes/$analyteId': typeof ShellAnalytesAnalyteIdRoute
  '/columns/$columnId': typeof ShellColumnsColumnIdRoute
  '/methods/$methodId': typeof ShellMethodsMethodIdRoute
  '/methods/compare': typeof ShellMethodsCompareRoute
  '/methods/new': typeof ShellMethodsNewRoute
  '/runs/$runId': typeof ShellRunsRunIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/reset': typeof ApiAuthResetRoute
  '/api/auth/reset-request': typeof ApiAuthResetRequestRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/columns/': typeof ShellColumnsIndexRoute
  '/methods/': typeof ShellMethodsIndexRoute
  '/runs/': typeof ShellRunsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof ShellAccountRoute
  '/admin': typeof ShellAdminRoute
  '/analytes': typeof ShellAnalytesRouteWithChildren
  '/batches': typeof ShellBatchesRoute
  '/overlay': typeof ShellOverlayRoute
  '/reports': typeof ShellReportsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/': typeof ShellIndexRoute
  '/analytes/$analyteId': typeof ShellAnalytesAnalyteIdRoute
  '/columns/$columnId': typeof ShellColumnsColumnIdRoute
  '/methods/$methodId': typeof ShellMethodsMethodIdRoute
  '/methods/compare': typeof ShellMethodsCompareRoute
  '/methods/new': typeof ShellMethodsNewRoute
  '/runs/$runId': typeof ShellRunsRunIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/reset': typeof ApiAuthResetRoute
  '/api/auth/reset-request': typeof ApiAuthResetRequestRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/columns': typeof ShellColumnsIndexRoute
  '/methods': typeof ShellMethodsIndexRoute
  '/runs': typeof ShellRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_shell/account': typeof ShellAccountRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/analytes': typeof ShellAnalytesRouteWithChildren
  '/_shell/batches': typeof ShellBatchesRoute
  '/_shell/overlay': typeof ShellOverlayRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/analytes/$analyteId': typeof ShellAnalytesAnalyteIdRoute
  '/_shell/columns/$columnId': typeof ShellColumnsColumnIdRoute
  '/_shell/methods/$methodId': typeof ShellMethodsMethodIdRoute
  '/_shell/methods/compare': typeof ShellMethodsCompareRoute
  '/_shell/methods/new': typeof ShellMethodsNewRoute
  '/_shell/runs/$runId': typeof ShellRunsRunIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/reset': typeof ApiAuthResetRoute
  '/api/auth/reset-request': typeof ApiAuthResetRequestRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/_shell/columns/': typeof ShellColumnsIndexRoute
  '/_shell/methods/': typeof ShellMethodsIndexRoute
  '/_shell/runs/': typeof ShellRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/admin'
    | '/analytes'
    | '/batches'
    | '/overlay'
    | '/reports'
    | '/shared/$token'
    | '/analytes/$analyteId'
    | '/columns/$columnId'
    | '/methods/$methodId'
    | '/methods/compare'
    | '/methods/new'
    | '/runs/$runId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/reset'
    | '/api/auth/reset-request'
    | '/api/auth/signup'
    | '/api/public/bootstrap-admin'
    | '/api/public/config'
    | '/columns/'
    | '/methods/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/admin'
    | '/analytes'
    | '/batches'
    | '/overlay'
    | '/reports'
    | '/shared/$token'
    | '/'
    | '/analytes/$analyteId'
    | '/columns/$columnId'
    | '/methods/$methodId'
    | '/methods/compare'
    | '/methods/new'
    | '/runs/$runId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/reset'
    | '/api/auth/reset-request'
    | '/api/auth/signup'
    | '/api/public/bootstrap-admin'
    | '/api/public/config'
    | '/columns'
    | '/methods'
    | '/runs'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_shell/account'
    | '/_shell/admin'
    | '/_shell/analytes'
    | '/_shell/batches'
    | '/_shell/overlay'
    | '/_shell/reports'
    | '/shared/$token'
    | '/_shell/'
    | '/_shell/analytes/$analyteId'
    | '/_shell/columns/$columnId'
    | '/_shell/methods/$methodId'
    | '/_shell/methods/compare'
    | '/_shell/methods/new'
    | '/_shell/runs/$runId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/reset'
    | '/api/auth/reset-request'
    | '/api/auth/signup'
    | '/api/public/bootstrap-admin'
    | '/api/public/config'
    | '/_shell/columns/'
    | '/_shell/methods/'
    | '/_shell/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SharedTokenRoute: typeof SharedTokenRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthResetRoute: typeof ApiAuthResetRoute
  ApiAuthResetRequestRoute: typeof ApiAuthResetRequestRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/overlay': {
      id: '/_shell/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof ShellOverlayRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/batches': {
      id: '/_shell/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof ShellBatchesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytes': {
      id: '/_shell/analytes'
      path: '/analytes'
      fullPath: '/analytes'
      preLoaderRoute: typeof ShellAnalytesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/account': {
      id: '/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShellAccountRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/runs/': {
      id: '/_shell/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof ShellRunsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/methods/': {
      id: '/_shell/methods/'
      path: '/methods'
      fullPath: '/methods/'
      preLoaderRoute: typeof ShellMethodsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/columns/': {
      id: '/_shell/columns/'
      path: '/columns'
      fullPath: '/columns/'
      preLoaderRoute: typeof ShellColumnsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public/config': {
      id: '/api/public/config'
      path: '/api/public/config'
      fullPath: '/api/public/config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-request': {
      id: '/api/auth/reset-request'
      path: '/api/auth/reset-request'
      fullPath: '/api/auth/reset-request'
      preLoaderRoute: typeof ApiAuthResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset': {
      id: '/api/auth/reset'
      path: '/api/auth/reset'
      fullPath: '/api/auth/reset'
      preLoaderRoute: typeof ApiAuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/runs/$runId': {
      id: '/_shell/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof ShellRunsRunIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/methods/new': {
      id: '/_shell/methods/new'
      path: '/methods/new'
      fullPath: '/methods/new'
      preLoaderRoute: typeof ShellMethodsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/methods/compare': {
      id: '/_shell/methods/compare'
      path: '/methods/compare'
      fullPath: '/methods/compare'
      preLoaderRoute: typeof ShellMethodsCompareRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/methods/$methodId': {
      id: '/_shell/methods/$methodId'
      path: '/methods/$methodId'
      fullPath: '/methods/$methodId'
      preLoaderRoute: typeof ShellMethodsMethodIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/columns/$columnId': {
      id: '/_shell/columns/$columnId'
      path: '/columns/$columnId'
      fullPath: '/columns/$columnId'
      preLoaderRoute: typeof ShellColumnsColumnIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytes/$analyteId': {
      id: '/_shell/analytes/$analyteId'
      path: '/$analyteId'
      fullPath: '/analytes/$analyteId'
      preLoaderRoute: typeof ShellAnalytesAnalyteIdRouteImport
      parentRoute: typeof ShellAnalytesRoute
    }
  }
}

interface ShellAnalytesRouteChildren {
  ShellAnalytesAnalyteIdRoute: typeof ShellAnalytesAnalyteIdRoute
}

const ShellAnalytesRouteChildren: ShellAnalytesRouteChildren = {
  ShellAnalytesAnalyteIdRoute: ShellAnalytesAnalyteIdRoute,
}

const ShellAnalytesRouteWithChildren = ShellAnalytesRoute._addFileChildren(
  ShellAnalytesRouteChildren,
)

interface ShellRouteChildren {
  ShellAccountRoute: typeof ShellAccountRoute
  ShellAdminRoute: typeof ShellAdminRoute
  ShellAnalytesRoute: typeof ShellAnalytesRouteWithChildren
  ShellBatchesRoute: typeof ShellBatchesRoute
  ShellOverlayRoute: typeof ShellOverlayRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellColumnsColumnIdRoute: typeof ShellColumnsColumnIdRoute
  ShellMethodsMethodIdRoute: typeof ShellMethodsMethodIdRoute
  ShellMethodsCompareRoute: typeof ShellMethodsCompareRoute
  ShellMethodsNewRoute: typeof ShellMethodsNewRoute
  ShellRunsRunIdRoute: typeof ShellRunsRunIdRoute
  ShellColumnsIndexRoute: typeof ShellColumnsIndexRoute
  ShellMethodsIndexRoute: typeof ShellMethodsIndexRoute
  ShellRunsIndexRoute: typeof ShellRunsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountRoute: ShellAccountRoute,
  ShellAdminRoute: ShellAdminRoute,
  ShellAnalytesRoute: ShellAnalytesRouteWithChildren,
  ShellBatchesRoute: ShellBatchesRoute,
  ShellOverlayRoute: ShellOverlayRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellColumnsColumnIdRoute: ShellColumnsColumnIdRoute,
  ShellMethodsMethodIdRoute: ShellMethodsMethodIdRoute,
  ShellMethodsCompareRoute: ShellMethodsCompareRoute,
  ShellMethodsNewRoute: ShellMethodsNewRoute,
  ShellRunsRunIdRoute: ShellRunsRunIdRoute,
  ShellColumnsIndexRoute: ShellColumnsIndexRoute,
  ShellMethodsIndexRoute: ShellMethodsIndexRoute,
  ShellRunsIndexRoute: ShellRunsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SharedTokenRoute: SharedTokenRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthResetRoute: ApiAuthResetRoute,
  ApiAuthResetRequestRoute: ApiAuthResetRequestRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
